table 'Product Lookup'
	lineageTag: 91162454-9505-4266-ba3b-33baf322bda1

	column ProductKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 543c3b36-05c2-4279-8814-d1dd4f25a43d
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5dd0b72b-0ad8-43f7-8ee2-16526740f6ac
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductSKU
		dataType: string
		lineageTag: 091585c1-e5b8-4c43-8ae4-8efec98d42ea
		summarizeBy: none
		sourceColumn: ProductSKU

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: fdc4e538-92ad-43ae-b55c-4f03701365b7
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column ModelName
		dataType: string
		lineageTag: 99efb591-6945-496d-b193-2dd771f77c16
		summarizeBy: none
		sourceColumn: ModelName

		annotation SummarizationSetBy = Automatic

	column ProductDescription
		dataType: string
		lineageTag: 87b44582-231d-46b7-bda2-6d4d28a59394
		summarizeBy: none
		sourceColumn: ProductDescription

		annotation SummarizationSetBy = Automatic

	column ProductColor
		dataType: string
		lineageTag: c0a05305-d66e-403b-ada7-3010fca92c5b
		summarizeBy: none
		sourceColumn: ProductColor

		annotation SummarizationSetBy = Automatic

	column ProductStyle
		dataType: string
		lineageTag: ecdbc6ed-e310-45e1-a032-7363b91cff97
		summarizeBy: none
		sourceColumn: ProductStyle

		annotation SummarizationSetBy = Automatic

	column ProductCost
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c076d874-f662-4bb7-873c-37b67f951f79
		summarizeBy: sum
		sourceColumn: ProductCost

		annotation SummarizationSetBy = Automatic

	column ProductPrice
		dataType: decimal
		formatString: "₦"#,0.00;-"₦"#,0.00;"₦"#,0.00
		lineageTag: 76095747-5394-4560-9667-ff9471d31d0e
		summarizeBy: sum
		sourceColumn: ProductPrice

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-NG"}

	column SKU-Type
		dataType: string
		lineageTag: bc1a9b17-428c-4e3e-8208-9e71f7458d5a
		summarizeBy: none
		sourceColumn: SKU-Type

		annotation SummarizationSetBy = Automatic

	column 'Discount Price'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 98908b11-702d-483d-bbc9-f42e1c6963a3
		summarizeBy: sum
		sourceColumn: Discount Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Price Point' =
			
			SWITCH(
			   TRUE(),
			   'Product Lookup'[ProductPrice]>500,"High",
			   'Product Lookup'[ProductPrice]>100,"Mid Range",
			   "low"
			)
		lineageTag: 4dd600df-72bb-4e1a-b5c5-a4e989a3f0b7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Category SKU' = ```
			
			 LEFT(
			    'Product Lookup'[ProductSKU],
			    SEARCH(
			        "-",
			        'Product Lookup'[ProductSKU],
			    )
			 -1
			 )
			```
		lineageTag: a35edea0-502b-4fa5-9617-11593063221f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Product Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\HP\Downloads\AdventureWorksRawData-230523-122034\AdventureWorks Raw Data\AdventureWorks Product Lookup.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", Int64.Type}, {"ProductSubcategoryKey", Int64.Type}, {"ProductSKU", type text}, {"ProductName", type text}, {"ModelName", type text}, {"ProductDescription", type text}, {"ProductColor", type text}, {"ProductSize", type text}, {"ProductStyle", type text}, {"ProductCost", type number}, {"ProductPrice", type number}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"ProductPrice", type number}, {"ProductCost", type number}}),
				    #"Changed to Currency" = Table.TransformColumnTypes(#"Changed Type1",{{"ProductCost", Currency.Type}, {"ProductPrice", Currency.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed to Currency",{"ProductSize"}),
				    #"Inserted text before delimeters" = Table.AddColumn(#"Removed Columns", "Text Before Delimiter", each Text.BeforeDelimiter([ProductSKU], "-", 1), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted text before delimeters",{{"Text Before Delimiter", "SKU-Type"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","0","NA",Replacer.ReplaceText,{"ProductStyle"}),
				    #"Inserted Multiplication" = Table.AddColumn(#"Replaced Value", "Multiplication", each [ProductPrice] * 0.9, Currency.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Multiplication",{{"Multiplication", "Discount Price"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

