table 'Sales Data 2022'
	lineageTag: f739856a-db0f-4526-adf3-e86cb37981c3

	column OrderDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 43ce8408-420e-4a5d-a521-48d08d9d98f0
		summarizeBy: none
		sourceColumn: OrderDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StockDate
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: a6124ee6-4de2-4800-bb7b-7956fd209852
		summarizeBy: none
		sourceColumn: StockDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderNumber
		dataType: string
		lineageTag: 87fb9bbd-eab2-400a-aa42-a7d978df111f
		summarizeBy: none
		sourceColumn: OrderNumber

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e885d0ab-2f46-42a6-8464-d6b381accd2c
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 87424da2-ca6d-446c-8256-009a3e1ae2ce
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2c14bee0-86c7-4f21-8fb4-172260599815
		summarizeBy: none
		sourceColumn: TerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderLineItem
		dataType: int64
		formatString: 0
		lineageTag: 84edbf9d-614e-45ca-94f6-4673ed2e1d78
		summarizeBy: sum
		sourceColumn: OrderLineItem

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: 82023b86-1bd0-42a2-a28b-7a9bb542f6a5
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column 'Quantity Type' =
			
			if(
			    'Sales Data 2022'[OrderQuantity] >1,
			    "Multiple items",
			    "Single Item"
			)
		lineageTag: 2fc21279-6fdd-458f-8c29-4078bc6853f7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sales Data 2022' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\HP\Downloads\AdventureWorksRawData-230523-122034\AdventureWorks Raw Data\AdventureWorks Sales Data 2022.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrderDate", type date}, {"StockDate", type date}, {"OrderNumber", type text}, {"ProductKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"TerritoryKey", Int64.Type}, {"OrderLineItem", Int64.Type}, {"OrderQuantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

